-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/import_requests (
  request_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  request_actor BIGINT UNSIGNED NOT NULL,
  request_timestamp BINARY(14) NOT NULL,
  request_source VARCHAR(255) NOT NULL,
  request_target VARCHAR(64) NOT NULL,
  request_reason BLOB NOT NULL,
  request_status ENUM(
    'complete', 'declined', 'failed',
    'inprogress', 'pending', 'starting'
  ) NOT NULL,
  request_locked TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  request_private TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  INDEX request_actor_timestamp (
    request_actor, request_timestamp
  ),
  INDEX request_timestamp (request_timestamp),
  INDEX request_target (request_target),
  INDEX request_status (request_status),
  PRIMARY KEY(request_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/import_request_comments (
  request_comment_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  request_comment_actor BIGINT UNSIGNED NOT NULL,
  request_comment_timestamp BINARY(14) NOT NULL,
  request_comment_text BLOB NOT NULL,
  INDEX request_id (request_id),
  INDEX request_comment_timestamp (request_comment_timestamp),
  PRIMARY KEY(request_comment_id)
) /*$wgDBTableOptions*/;
